
[general]
	#Hard cap on how many tubes can exist in a contiguous network of tubes. If a player attempts to make a network of greater size from this value, not all tubes in the attempted network will become part of that network.
	#Range: 1 ~ 10000
	hard_tube_cap = 200
	#Base time in ticks that a moving itemstack spends in each individual tube block. Adjusted by other factors.
	#Range: 1 ~ 72000
	ticks_in_tube = 10
	#Osmosis filter automatic item transfer rate in ticks per item. The default value of 8 is the same as vanilla hoppers.
	#Range: > 1
	osmosis_filter_transfer_rate = 8
	#Soft cap on how many tubes can exist in a contiguous network of tubes. Items are transported slowlier in networks of greater size than this value.
	#Range: 1 ~ 10000
	soft_tube_cap = 100
	#Max items that can fit in a single tube. A tube block will break of the number of itemstacks contained with them is greater than this value, dropping their items on the ground
	#Range: > 1
	max_items_in_tube = 2147483647

